name = "simple-video-player"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

#kv_namespaces = [
#  { binding = "VIDEO_CONFIG", id = "b8d2d6aa6599421f8e2ac45ce6be4987"}
#]
